### ISSUE TITLE
Question: what's the purpose of the pre_build/build step?

### ISSUE THREAD

**Issue by elie222** [aaronwht/docker-typescript-mongodb#1]
This is the current `buildspec.yml`:

```
version: 0.2

phases:
    install:
        runtime-versions:
            docker: 18
    pre_build:
        commands:
        - npm install typescript --g
        - npm ci && npm cache clean --force
    build:
        commands:
        - tsc
artifacts:
    type: zip
    files:
        - package.json
        - package-lock.json
        - tsconfig.json
        - Dockerrun.aws.json
        - 'dist/**/*'
        - Dockerfile
```

Don't we just need the zipped artifact which is then sent to Elastic Beanstalk which builds the Docker container and completes the deploy?
What's the purpose of everything prior to that?
